### ISSUE TITLE
docker-compose.yml updates for 1496 byte MTU

### ISSUE THREAD

**Issue by sdonovan1985** [atlanticwave-sdx/atlanticwave-proto#129]
The docker-compose.yml files for the ATL and MIA sites need to be updated to specify the new MTU as was done for the pseudo-dtn [docker image](https://github.com/atlanticwave-sdx/atlanticwave-proto/blob/master/docker/pseudo_dtn/docker-compose.yml.atl):
```
networks:                                
  default:                               
    driver: bridge                       
    driver_opts:                         
      com.docker.network.driver.mtu: 1496
```

This is related to #110.
